# Generated by Django 3.1.13 on 2021-07-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='type',
        ),
    ]
