# Generated by Django 3.1.13 on 2021-07-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_orderlineitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
