# Generated by Django 3.1.13 on 2021-07-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_orderlineitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_portfolio', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('OrderLineItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.orderlineitem')),
            ],
        ),
    ]
