# Generated by Django 3.1.13 on 2021-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='complexity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='user_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
