# Generated by Django 3.1.13 on 2021-07-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210712_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
