# Generated by Django 3.1.13 on 2021-07-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('logo', 'Logo'), ('poster', 'Poster'), ('icon', 'Icon'), ('banner', 'Banner')], max_length=254)),
                ('friendly_name', models.CharField(blank=True, default='default', max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.category'),
        ),
    ]
