# Generated by Django 3.1.13 on 2021-07-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_orderlineitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='display_in_portfolio',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
