# Generated by Django 3.1.13 on 2021-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20210715_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='variations',
            field=models.DecimalField(choices=[(1.0, 'Single'), (1.25, '2  (+25%)'), (1.5, '3  (+50%)'), (1.75, '4  (+75%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
