# Generated by Django 3.1.13 on 2021-07-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_auto_20210717_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_cart',
        ),
    ]
