# Generated by Django 3.1.13 on 2021-07-11 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Logo'), (2, 'Poster'), (3, 'Icon'), (4, 'Banner')], max_length=254)),
                ('friendly_name', models.CharField(blank=True, default='default', max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254, null=True)),
                ('complexity', models.DecimalField(choices=[(1.0, 'Normal'), (1.25, 'Advanced (+25%)'), (1.5, 'Complex (+50%)')], decimal_places=2, default=1, max_digits=3)),
                ('variations', models.DecimalField(choices=[(1.0, 'Single'), (1.25, '2  (+25%)'), (1.5, '3  (+50%)'), (1.75, '3  (+75%)')], decimal_places=2, default=1, max_digits=3)),
                ('user_description', models.TextField(default='')),
                ('fast_delivery', models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True)),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('price_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('type', models.DecimalField(choices=[(1, 'Logo'), (2, 'Poster'), (3, 'Icon'), (4, 'Banner')], decimal_places=1, default=1, max_digits=3)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.category')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
            ],
        ),
    ]
