# Generated by Django 3.1.13 on 2021-07-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_total',
            new_name='lineitem_total',
        ),
    ]
