# Generated by Django 3.1.13 on 2021-07-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210711_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
