# Generated by Django 3.1.13 on 2021-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('logo', 'Logo'), ('poster', 'Poster'), ('icon', 'Icon'), ('banner', 'Banner')], max_length=254),
        ),
    ]
