# Generated by Django 3.1.13 on 2021-07-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20210714_2113'),
        ('portfolio', '0004_auto_20210712_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_portfolio', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('name', models.CharField(default='', max_length=254)),
                ('friendly_name', models.CharField(default='', max_length=254, null=True)),
                ('category', models.CharField(default=0, max_length=254)),
                ('complexity', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('variations', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('user_description', models.TextField(default='')),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('lineitem_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('OrderLineItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.orderlineitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
