# Generated by Django 3.1.13 on 2021-07-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210714_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default=0, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='complexity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True),
        ),
    ]
