# Generated by Django 3.1.13 on 2021-07-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210714_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_in_portfolio',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
