# Generated by Django 3.1.13 on 2021-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_product_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
